# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-03 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ODCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=False)),
                ('phone', models.CharField(blank=False)),
                ('address', models.CharField(max_length=128)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Dibuat')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Waktu diedit')),
                ('picture', models.ImageField(upload_to = 'pic_folder/', default = 'pic_folder/None/no-img.jpg')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Soft Delete')),
                ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
