# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='odcustomer',
            options={'verbose_name_plural': 'Customer'},
        ),
        migrations.AlterField(
            model_name='odcustomer',
            name='picture',
            field=models.CharField(max_length=128),
        ),
    ]
